# Generated by Django 5.2.4 on 2025-07-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('name', models.CharField(help_text='Name of the category.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional. Description of the category.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible to customers.')),
            ],
            options={
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('image', models.ImageField(blank=True, help_text='Optional Image.', null=True, upload_to='images/')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility.', max_length=255)),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional. Detailed description of the item.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total quantity in stock.')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number.')),
                ('min_order_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity that can be ordered at once.')),
                ('max_order_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity that can be ordered at once (optional).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and available for purchase.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured item.')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price of the item.', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Optional. Discount amount to subtract from the original price.', max_digits=5)),
                ('category', models.ForeignKey(help_text='Category this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('image', models.ImageField(blank=True, help_text='Optional Image.', null=True, upload_to='images/')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image should be displayed.')),
                ('item', models.ForeignKey(help_text='Item this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='stock.stockitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
