# Generated by Django 5.2.4 on 2025-07-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('name', models.CharField(help_text="Category name that groups related list items (e.g., 'Electronics', 'Furniture').", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'List categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this item, including features or specifications (optional).')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.listcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
