# Generated by Django 5.2.4 on 2025-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcategory',
            name='bootstrap_icon',
            field=models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='bootstrap_icon',
            field=models.CharField(blank=True, help_text="Optional Bootstrap icon class. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255),
        ),
    ]
