# Generated by Django 5.2.4 on 2025-07-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_listcategory_bootstrap_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcategory',
            name='bootstrap_icon',
        ),
    ]
