# Generated by Django 5.2.4 on 2025-07-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_listcategory_bootstrap_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'List categories'},
        ),
        migrations.RemoveField(
            model_name='listcategory',
            name='display_order',
        ),
    ]
