# Generated by Django 5.2.4 on 2025-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaddress',
            name='icon',
            field=models.CharField(blank=True, editable=False, help_text='Bootstrap icon class (auto-populated based on name)', max_length=50),
        ),
    ]
