# Generated by Django 5.2.4 on 2025-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_socialmediaaddress_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicaladdress',
            options={'ordering': ['display_order', 'label', 'city']},
        ),
    ]
