name: Deploy Django App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Set strict error handling
          set -e
          
          # Set environment variables
          export DJANGO_SETTINGS_MODULE=your_project.settings.production
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          
          # Navigate to your project directory (update this path)
          cd /path/to/your/django/project
          
          # Pull latest changes
          echo "Pulling latest changes..."
          git pull origin main
          
          # Install/update Python dependencies with Poetry
          echo "Installing Python dependencies with Poetry..."
          poetry install --only=main --no-dev
          
          # Django management commands (using poetry run)
          echo "Running makemigrations..."
          poetry run python manage.py makemigrations --check || poetry run python manage.py makemigrations
          
          echo "Running migrate..."
          poetry run python manage.py migrate --noinput
          
          echo "Setting up groups..."
          poetry run python manage.py setup_groups
          
          echo "Seeding database..."
          poetry run python manage.py seed
          
          # Frontend dependencies and build
          echo "Installing npm dependencies using custom Django command..."
          poetry run python manage.py npm install
          
          echo "Building static files..."
          poetry run python manage.py buildstatic
          
          # Restart your web server (uncomment the appropriate line)
          echo "Restarting services..."
          # For systemd service:
          sudo systemctl restart your-django-app
          
          # For supervisor:
          # sudo supervisorctl restart your-django-app
          
          # For gunicorn with systemd:
          # sudo systemctl restart gunicorn
          
          # For nginx (if needed):
          # sudo systemctl reload nginx
          
          echo "Deployment completed successfully!"